### ISSUE TITLE
KeyErrors

### ISSUE THREAD

**Issue by uluyol** [goelayu/NSDi-17#11]
I'm seeing lot's of errors like this:
```
got an error with task flexbasic-any-w3x-s2.5: Command '['/w/avail-run/comparing_latencies.py', '--op-count', '100000', '/mnt/cdata0/auto-fs-avail-results/Global/results-NAS-6-FAIL-1-id172224/solutions/flexbasic-any-w3x-s2.5.final', '/mnt/cdata0/auto-fs-avail-results/Global/results-NAS-6-FAIL-1-id172224/simulations/single/flexbasic-any-w3x-s2.5']' returned non-zero exit status 1
Read quorum size 0
Write quorum size 0
Access set ['az/centralus', 'az/centralindia', 'az/eastasia', 'az/koreasouth', 'az/southindia']
List of replicas ['az/canadacentral', 'az/eastasia', 'az/southeastasia', 'az/westus2']
Flexible paxos enabled True
read quorums [['az/eastasia', 'az/southeastasia'], ['az/canadacentral', 'az/westus2'], ['az/eastasia', 'az/southeastasia'], ['az/eastasia', 'az/southeastasia'], ['az/eastasia', 'az/southeastasia']]
write quorums [['az/canadacentral', 'az/eastasia', 'az/southeastasia'], ['az/eastasia', 'az/westus2'], ['az/eastasia', 'az/southeastasia', 'az/westus2'], ['az/eastasia', 'az/southeastasia', 'az/westus2'], ['az/eastasia', 'az/westus2']]
Running simmulation for specific quorum system...
Traceback (most recent call last):
Reading network latency file...
  File "/w/avail-run/comparing_latencies.py", line 536, in <module>
    main()
  File "/w/avail-run/comparing_latencies.py", line 520, in main
    sampleGet = GetRequestGenerator(networkLatencies, storageLatencies[0], frontend, listOfReplicas, quorumSystem, numberOfSplits)
  File "/w/avail-run/comparing_latencies.py", line 325, in GetRequestGenerator
    storageLatency = random.choice(readStorageLatencies[dc])
KeyError: 'az/canadacentral'
```

Might have something to do with trimming data for DCs not in use.

**Comment by goelayu** [comment]
Resolved with [this](https://github.com/goelayu/NSDi-17/commit/cb112eef2cadffdabf3281935e93b0defba642c2) commit.
